### ISSUE TITLE
Clase en content.js

### ISSUE THREAD

**Issue by gbosetti** [ulises-jeremias/webextension#10]
Algo parecido a la observación en background.js: acá resolvés un montón de cosas adentro del listener que estaría bueno tenerlo dentro de un mensaje, al que simplemente llamás desde el listener. Además, de esa manera podrías tener más de un mensaje por listener. Por ejemplo, si acá tuvieras un mensaje para abrir el panel y otro para cerrarlo, y pasaras el mensaje a ejecutar por parámetro, podrías enviarle ese mensaje específico a la instancia que tengas de este lado. Y cómo a partir de un string? Bueno, supongamos que tenés una clase Empleado:

```
class Employee {
  constructor(firstName, familyName) {
    this._firstName = firstName;
    this._familyName = familyName;
  }
  getFullName() {
    return `${this._firstName} ${this._familyName}`;
  }
}

```
Creás una instancia:
`var emp = new Employee("Violencia", "Rivas");
`
Y podrías enviarle el mensaje getFullName() haciendo:
`emp.getFullName();
`
Pero también:
`emp["getFullName"]()
`
Voilà!

**Comment by ulises-jeremias** [comment]
Respondo esta issue en los comentarios de la issue #11 !
