### ISSUE TITLE
Nombre de clase más específico para ContentHandler

### ISSUE THREAD

**Issue by gbosetti** [ulises-jeremias/webextension#11]
Cuál es la responsabilidad de ContentHandler? Content es muy genérico, podría imaginarme cualquier tipo de contenido. Te deja agregar cualquier cosa? Un botón? Un sidebar? Un panel? Lo mismo que "handler": para manejar qué exactamente?

**Comment by ulises-jeremias** [comment]
Claramente no estaban muy claras las responsabilidades de ContentHandler, por lo que se optó por hacer un refactoring de los content_scripts, quedando de la siguiente forma:

El código presente en el content.js es

```js
"use strict"

[. . .]

browser.runtime.onMessage.addListener(async message => {
  const contentManager = new ContentManager(message);
  await contentManager[message.command]();
});
```

donde `ContentManager` es una clase que provee un protocolo especifico para resolver los mensajes que llegar al _content.js_ (por el momento los mensajes `run` y `reset`). El mismo define en su estado interno una instancia de la clase `PanelComponent` generada a partir de un builder, instancia de `PanelBuilder`. En el componente se definen comportamientos de "renderizado" de la información entre otros métodos con el fin de obtener la información (los títulos) y mostrarlos en el panel, así como también la capacidad de remover el panel del DOM. 

Por el momento los cambios referidos a esta issue se encuentran en la rama development hasta terminar de documentar las clases y métodos modificados.

**Comment by gbosetti** [comment]
Hola Ulises, te respondo solo mirando el código del comentario. Buenisimo que hayas creado el ContentManager. Ahora, me parece que śería mejor que la instancia la crees fuera del listener, para que no tengas que crearla cada vez que llamás a un mensaje:

```
const contentManager = new ContentManager(message);
browser.runtime.onMessage.addListener(async message => {
  await contentManager[message.command]();
});
```
Otro detalle acá es que habría que chequear el uso del await, porque no siempre vas a necesitar esperar a la ejecución de un mensaje... Y estarías haciendo esperar a su resolución para continuar, cuando por ahi no tiene sentido esperar. Es decir:

const contentManager = new ContentManager(message);
browser.runtime.onMessage.addListener(async message => {
  contentManager[message.command]();
});

**Comment by ulises-jeremias** [comment]
Hola Gabi, respecto del await tenés razón en que no es necesario esperar en ese caso, ahora mismo lo cambio en el código. Por otro lado, en el código la instancia de ContentManager se define a partir del mensaje `message` que recibe, ya que en el mismo recibe el `tagName` a utilizar. De igual forma, el tagName no resulta necesario para el mensaje `reset` del ContentHandler, pero si para generar la instancia del `ContentComponent`. La idea era que se delegue la responsabilidad de removerse al componente, pero podría ver de que forma puedo resolverlo para que la instancia pueda ser creada sin la necesidad del tagName.

**Comment by ulises-jeremias** [comment]
Hola Gabi, al final logré hacer algunos cambios mínimos para que la clase `ContentManager` sea instanciada solo una vez. El código del content.js quedaría así

```js
"use strict"

const contentManager = new ContentManager();

browser.runtime.onMessage.addListener(async message => {
  message.tagName && contentManager.buildPanel(message.tagName);
  contentManager[message.command]();
});
```

La idea de esto es que cuando la aplicación está corriendo no sea necesario el tagName para quitar el panel flotante, por lo que solo se hace build del panel cuando el mismo esté seteado (osea, el tagName), sinó se trabaja con el panel que ya se tiene en el estado interno de la instancia de `ContentManager` enviándole el mensaje `remove`.
