### ISSUE TITLE
Clase en background.js

### ISSUE THREAD

**Issue by gbosetti** [ulises-jeremias/webextension#8]
Hola! La extensión viene genial. Chusmeate que en ese file tenés base, path, paramName y running (ver issue del state) que podrían ser tranquilamente atributos en el contexto de una clase. Además, lo que resolvés dentro de los listeners podría ser parte del comportamiento de esa misma clase. De ese modo, lo único que asociás al como listener es un mensaje a una instancia de esa clase.

**Comment by ulises-jeremias** [comment]
Hola! Genial, lo voy cambiando entonces y voy documentando los cambios referidos a esta issue en comentarios

**Comment by ulises-jeremias** [comment]
Se agregó la clase `BackgroundManager`, que tiene como atributos una _configuración_ conformada por un urlBase, path, paramName y tagName, y un _estado actual_, instancia del tipo `BackgroundState` (se comenta en la issue #9 ). El mismo define el comportamiento de la extensión en base a su estado. 

La clase se instancia y utiliza en el `background/background.js`.

**Comment by ulises-jeremias** [comment]
Ya se hizo merge a master!

**Comment by gbosetti** [comment]
Genial, aunque si una instancia de BackgroundManager requiere tener seteado un estado por defecto para funcionar bien, entonces se lo deberías pasar por el constructor en lugar de usando setCurrentState.

const backgroundManager = new BackgroundManager({
  base: 'https://scholar.google.com',
  path: '/scholar',
  paramName: 'q',
  tagName: 'h1',
  initialState: new LalalaState()
});

**Comment by ulises-jeremias** [comment]
Ahh, me parece bien, no lo había tenido en cuenta!
