### ISSUE TITLE
State en background.js

### ISSUE THREAD

**Issue by gbosetti** [ulises-jeremias/webextension#9]
En lugar de tener running estaría bueno que esa nueva clase, que va a resultar del issue 1, tenga un state. Entonces, de acuerdo al estado en el que se encuentra, sabe si mandar el mensaje para crear panel o para hacerlo desaparecer. De ese modo, no estás pasando un booleano y resolviendo qué hacer con el desde el content. AHora, te vas a encontrar con el problema de c'omo identificar mensajes de un lado a otro. Va en el siguiente issue.

**Comment by ulises-jeremias** [comment]
Para esta issue se creó una jerarquía de clases para definir el estado de la clase `BackgroundManager`. La misma se compone de dos clases que modelan estados concretos, `RunningState` y `StoppedState`, ambas herederas de la clase `BackgroundState`. Se utiliza sintaxis de clases de ES6 para la definición de las clases, pero se juega un poco con los prototipos y bindings dinámicos para definir de forma no tan clásica el patrón state.

Por el momento los cambios referidos a esta issue se encuentran en la rama `development` hasta terminar de documentar las clases y métodos modificados.

**Comment by gbosetti** [comment]
Esto lo charlamos por vivo o por skype, lo dejo abierto para acordarme.
